export const metadata = {
  title: "Privacy Policy - SG Weather",
  description: "Privacy Policy of SG Weather",
};

export const PrivacyDefault = () => {
  return (
    <main className="centerbox">
      <wa-card with-header class="card-header">
        <h2 slot="header">Privacy Policy</h2>

        <h3>Device Identifier</h3>
        <p>
          No data of you is collected nor processed. <br />
          A unique identifier is generated on your device to identify the device.<br />
          The identifier is generated by Apple and will be used to ensure uniqueness of data.<br />
        </p>

        <h3>Location Privacy</h3>
        <p>
          A rough estimation of the place you are in is calculated on your phone and then request for the data you need. <br />
        </p>
      </wa-card>
    </main>
  );
}

export default PrivacyDefault;